### ISSUE TITLE
Add linting, CI checks, LICENCE and add branch protections as per Multisig v1 repo

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/MultisigControl#122]
### Issue

To ensure that the Multisig V2 repo is ready to open source we need to carry out the following tasks

#### Tasks:

- [x] branch protections as per Multisig v1 repo
- [ ] Add [linting, CI checks](https://github.com/vegaprotocol/MultisigControl/tree/develop/.github/workflows) and other config files.
- [ ] Update the licence file as per [multisig v1 repo licence](https://github.com/vegaprotocol/MultisigControl/blob/develop/LICENSE)
